---
apiVersion: v2
appVersion: 0.79.0-1222
description: |
  Dell EMC ObjectScale is highly scalable, and high performance S3 compatible object storage platform.
name: ecs-cluster
version: 0.79.0-1222
icon: https://avatars0.githubusercontent.com/u/12926680
maintainers:
  - name: Dell EMC
    url: http://dellemc.com
dependencies:
  - name: ecs-monitoring
    # rfw-update-next ecs-monitoring-helm-chart
    version: 3.7.0-1304.1346960d # no_auto_change__monitoring_auto_change
    condition: global.monitoring.enabled
    repository: http://asdrepo.isus.emc.com:8081/artifactory/objectscale-helm-dev/
  - name: rsyslog-client
    repository: http://asdrepo.isus.emc.com:8081/artifactory/objectscale-helm-dev/
    # rfw-update-next rsyslog-client-helm-chart
    version: 3.7.0-1304.1346960d # no_auto_change__monitoring_auto_change
  - name: common-lib
    version: 0.79.0-1222
    repository: file://../common-lib
