---
apiVersion: v2
appVersion: 0.79.0-1239
description: |
  Dell EMC ObjectScale is highly scalable, and high performance S3 compatible object storage platform.
name: ecs-cluster
version: 0.79.0-1239
icon: https://avatars0.githubusercontent.com/u/12926680
maintainers:
  - name: Dell EMC
    url: http://dellemc.com
dependencies:
  - name: ecs-monitoring
    # rfw-update-next ecs-monitoring-helm-chart
    version: 3.7.0-1284.94838a58 # no_auto_change__monitoring_auto_change
    condition: global.monitoring.enabled
    repository: https://asdrepo.isus.emc.com/artifactory/objectscale-helm-build/
  - name: rsyslog-client
    repository: https://asdrepo.isus.emc.com/artifactory/objectscale-helm-build/
    # rfw-update-next rsyslog-client-helm-chart
    version: 3.7.0-1284.94838a58 # no_auto_change__monitoring_auto_change
  - name: common-lib
    version: 0.79.0-1239
    repository: file://../common-lib
