---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-healthchecks
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.registrySecret }}
imagePullSecrets:
  - name: {{ .Values.global.registrySecret }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-healthchecks
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
rules:
  - apiGroups:
      - app.k8s.io
    resources:
      - applications
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-healthchecks
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-healthchecks
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-healthchecks
  apiGroup: rbac.authorization.k8s.io
