---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-injector-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "logging-injector"
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: nautilus
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_"}}
    release: {{ .Release.Name }}
  annotations:
    com.dellemc.kahm.subscribed: "true"
data:
  health: |-
    spec:
      - name: pre-update
        container: {{ .Values.global.registry }}/{{ .Values.healthChecks.preUpdate.image.repository }}:{{ default .Chart.Version .Values.healthChecks.preUpdate.image.tag }}
        serviceaccount: {{ .Release.Name }}-healthchecks
        timelimit: "5m"
        reason: "pre-update"
        symptomID: "DECKS-HC-1000"
        args:
          - -target-version
          - {{ default .Chart.Version .Values.healthChecks.preUpdate.image.tag }}