---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supportassist-{{required "product must be specified" .Values.product}}-default-properties
  namespace: {{.Release.namespace}}
  labels:
    app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
{{ include "supportassist.labels" . | indent 4 }}
# yamllint disable-rule:colons
data:
  DefaultProperties.json: |
    # ESE Static configuration. It is simple JSON, but
    # may contain comments prefixed by '#'
    # For property information, visit: https://confluence.gtie.dell.com/display/LCOM/ESE+Configuration
    {
        "ipAddress": "0.0.0.0",
        "port": "8080",
        "useSSL": false,
        "productFrontendUri": "http://supportassist-{{.Values.product}}-ese-callback.{{.Release.Namespace}}.svc.cluster.local:9447",
        # Could also be HTTPS: "productFrontendUri": "https://supportassist-{{.Values.product}}.{{.Release.Namespace}}.svc.cluster.local:8447",
        "productFrontendPrefix": "{{.Values.product}}",
        "productFrontendType": "webrest",
        "srsTransferType": "{{.Values.product | upper}}"
    }
---
apiVersion: v1
kind: Service
metadata:
  name: supportassist-{{.Values.product}}
  namespace: {{.Release.namespace}}
  labels:
    app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
{{ include "supportassist.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: secure
    port: 9447
    targetPort: secure
    protocol: TCP
  - name: insecure
    port: 8080
    targetPort: insecure
    protocol: TCP
  selector:
    app.kubernetes.io/name: supportassist-{{.Values.product}}
    app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supportassist-{{.Values.product}}-persistentdata
  namespace: {{.Release.namespace}}
  labels:
    app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
{{ include "supportassist.labels" . | indent 4 }}
spec:
  {{- if .Values.global.storageClassName}}
  storageClassName: {{.Values.global.storageClassName}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supportassist-{{.Values.product}}
  namespace: {{.Release.namespace}}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
{{ include "supportassist.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
      app.kubernetes.io/name: supportassist-{{.Values.product}}
      io.kompose.service: ese-store
  strategy:
    type: Recreate
  template:
    metadata:
      name: supportassist-{{.Values.product}}
      namespace: {{.Release.namespace}}
      labels:
        app.kubernetes.io/component: supportassist-{{.Values.product}}-ese
        app.kubernetes.io/name: supportassist-{{.Values.product}}
        io.kompose.service: ese-store
{{ include "supportassist.labels" . | indent 8 }}
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
    spec:
      # to allow mounts and ownership as eseservice uid (999)
      # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: supportassist-{{.Values.product}}
        # image: <docker_registry>/dell-supportassist-ese:2.0.3
        image: {{.Values.global.registry}}/{{.Values.image.repository}}:{{default .Values.tag .Values.image.tag}}
        imagePullPolicy: {{default .Values.image.pullPolicy .Values.pullPolicy}}
        command: ["/opt/ese/bin/entrypoint.sh"]
        ports:
        - containerPort: 9447
          name: secure
          protocol: TCP
        - containerPort: 8080
          name: insecure
          protocol: TCP
        volumeMounts:
          - name: supportassist-{{.Values.product}}-persistentdata
            mountPath: /opt/ese/var
          - name: supportassist-{{.Values.product}}-default-properties
            mountPath: /opt/ese/etc/DefaultProperties.json
            subPath: DefaultProperties.json
          - name: supportassist-{{.Values.product}}-store-claim0
            mountPath: /opt/ese/data
        securityContext:
          runAsUser: 999
        env:
        - name: ESE_USER
          value: "eseservice"
        - name: REGISTRY_SECRET
          value: {{.Values.global.registrySecret}}
      - name: ese-store
        image: {{ .Values.global.registry }}/{{.Values.eseStore.image.repository }}:{{default .Values.tag .Values.eseStore.image.tag }}
        imagePullPolicy: {{ default .Values.pullPolicy .Values.eseStore.image.pullPolicy }}
        command: ["/usr/local/bin/run-nginx.sh"]
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: {{.Values.eseStore.containerPort}}
        resources: {}
        volumeMounts:
        - mountPath: /opt/secure/data
          name: supportassist-{{.Values.product}}-store-claim0
        env:
        - name: REGISTRY_SECRET
          value: {{.Values.global.registrySecret}}
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: supportassist-{{.Values.product}}-store-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: supportassist-{{.Values.product}}-store-secret
              key: password
        - name: SALT
          valueFrom:
            secretKeyRef:
              name: supportassist-{{.Values.product}}-store-secret
              key: salt
      restartPolicy: Always
      volumes:
      - name: supportassist-{{.Values.product}}-persistentdata
        persistentVolumeClaim:
          claimName: supportassist-{{.Values.product}}-persistentdata
      - name: supportassist-{{.Values.product}}-default-properties
        configMap:
          name: supportassist-{{.Values.product}}-default-properties
      - name: supportassist-{{.Values.product}}-store-claim0
        persistentVolumeClaim:
          claimName: supportassist-{{.Values.product}}-store-claim0
{{- if .Values.global.registrySecret }}
      imagePullSecrets:
      - name: {{ .Values.global.registrySecret }}
{{- end }}
