
{{- if .Values.useCustomValues }}
---
## Used to create custom values for objectscale-manager upgrades
global:
  {{- if .Values.global.registrySecret }}
  registrySecret: {{ .Values.global.registrySecret }}
  {{- end }}

  registry: {{ .Values.global.registry }}

  watchAllNamespaces: {{ .Values.global.watchAllNamespaces }}

  platform: {{ .Values.global.platform }}

  storageClassName: {{ .Values.global.storageClassName }}

  monitoring_registry: {{ .Values.global.monitoring_registry }}

  monitoring:
    enabled: {{ .Values.global.monitoring.enabled }}

{{- if .Values.image }}

image:
  tag: {{ .Values.image.tag }}
{{- end }}

hooks:
  registry: {{ .Values.hooks.registry }}

federation:
  enabled: {{ .Values.federation.enabled }}

ecs-monitoring:
  influxdb:
    persistence:
      storageClassName: {{ index .Values "ecs-monitoring" "influxdb" "persistence" "storageClassName" }}

objectscale-monitoring:
  influxdb:
    persistence:
      storageClassName: {{ index .Values "objectscale-monitoring" "influxdb" "persistence" "storageClassName" }}
  rsyslog:
    persistence:
      storageClassName: {{ index .Values "objectscale-monitoring" "rsyslog" "persistence" "storageClassName" }}

objectscale-gateway:
  enabled: {{ index .Values "objectscale-gateway" "enabled" }}

createApplicationResource: {{ .Values.createApplicationResource }}


{{- if .Values.objectscale_manager }}
## pull in any other custom values from the builder set with --set objectscale_manager.image.tag=best-tag-evah
{{ toYaml .Values.objectscale_manager }}
{{- end }}


{{- end }}