apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceprocedures.ecs.dellemc.com
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: objectscale-manager
    app.kubernetes.io/component: objectscale-operator
    app.kubernetes.io/part-of: objectscale-manager
    app.kubernetes.io/managed-by: nautilus
spec:
  group: ecs.dellemc.com
  names:
    kind: ServiceProcedure
    listKind: ServiceProcedureList
    plural: serviceprocedures
    singular: serviceprocedure
  scope: Namespaced
  additionalPrinterColumns:
    - name: STATUS
      type: string
      description: The status of service procedure
      JSONPath: .status.reason
    - description: The creation date
      JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ServiceProcedure is the Schema for the serviceprocedures API
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          description: ServiceProcedureSpec defines the desired state of ServiceProcedure
          properties:
            diskInfo:
              description: ObjectInfo defines objects name and UUID
              properties:
                name:
                  type: string
                uuid:
                  type: string
              type: object
            information:
              type: string
            nodeInfo:
              description: ObjectInfo defines objects name and UUID
              properties:
                name:
                  type: string
                uuid:
                  type: string
              type: object
            podsInfo:
              items:
                description: ObjectInfo defines objects name and UUID
                properties:
                  name:
                    type: string
                  uuid:
                    type: string
                type: object
              type: array
            type:
              type: string
          required:
          - type
          type: object
        status:
          description: ServiceProcedureStatus defines the observed state of ServiceProcedure
          properties:
            message:
              type: string
            reason:
              type: string
          required:
          - reason
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
