---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkconnections.ecs.dellemc.com
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: objectscale-manager
    app.kubernetes.io/component: objectscale-operator
    app.kubernetes.io/part-of: objectscale-manager
    app.kubernetes.io/managed-by: nautilus
spec:
  group: ecs.dellemc.com
  names:
    kind: NetworkConnection
    listKind: NetworkConnectionList
    plural: networkconnections
    singular: networkconnection
    shortNames:
    - tls
    - cert
    - connection
    - netcon
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: PHASE
    type: string
    description: The current phase of cluster operation
    JSONPath: .status.phase
