---
apiVersion: v2
appVersion: 0.79.0-1222
description: A Helm chart for Dell EMC Federation Service
name: objectscale-federation
version: 0.79.0-1222
icon: https://avatars0.githubusercontent.com/u/12926680
maintainers:
  - name: Dell EMC
    url: http://dellemc.com
dependencies:
  - name: common-monitoring-lib
    repository: http://asdrepo.isus.emc.com:8081/artifactory/objectscale-helm-dev/
    # rfw-update-next common-monitoring-lib-helm-chart
    version: 3.7.0-1304.1346960d # no_auto_change__monitoring_auto_change
  - name: common-lib
    version: 0.79.0-1222
    repository: file://../common-lib
