---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-dcm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dcm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dcm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dcm.selectorLabels" . | nindent 8 }}
{{ include "common-monitoring-lib.logging-inject-labels" . | indent 8 }}
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
    spec:
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "atlas,flex,dns"
          - name: ATLAS_SERVICE_HOSTNAME
            value: {{ include "dcm.name" .}}-atlas-client
          - name: MY_POD_NAME
            valueFrom:
             fieldRef:
              fieldPath: metadata.name
          - name: MY_OBJECTSCALE_NAMESPACE
            valueFrom:
             fieldRef:
              fieldPath: metadata.namespace
          - name: MY_POD_NAMESPACE
            valueFrom:
             fieldRef:
              fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
             fieldRef:
              fieldPath: status.podIP
          image: "{{ default  .Values.global.registry .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9026
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.probePath }}
              port: http
            failureThreshold: {{ .Values.livenessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 60 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.probePath }}
              port: http
            failureThreshold: {{ .Values.readinessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 60 }}
          volumeMounts:
            - name: log
              mountPath: /var/log
            - name: config
              mountPath: /opt/storageos/conf/dcm-log4j2.xml
              subPath: dcm-log4j2.xml
            - name: encryptionkey
              mountPath: /opt/secure/encryptionkey
              readOnly: true
            - name: mgmt-shared-secret
              mountPath: "/etc/mgmt/sharedsecret"
            - name: trusted-anchors-secret
              mountPath: "/etc/mgmt/trustedanchors"
      volumes:
        - name: log
          emptyDir: {}
        - name: config
          configMap:
            name: dcm-log-config
        - name: encryptionkey
          secret:
            secretName: {{ .Release.Name }}-dcm-encryption-key
        - name: mgmt-shared-secret
          secret:
            secretName: mgmt-servicelogin-shared-secret
        - name: trusted-anchors-secret
          secret:
            secretName: objectscale-federation-trusted-anchors

