---
apiVersion: v2
name: objectscale-vsphere
version: 0.78.0-1209
appVersion: 0.78.0-1209
description: ObjectScale VMware vSphere Plugin
maintainers:
  - name: Dell EMC
    url: https://dellemc.com
dependencies:
  - name: objectscale-portal
    version: 0.78.0-1209
    repository: file://../objectscale-portal
