---
{{- if eq .Values.global.platform "VMware" }}
apiVersion: v1
kind: Service
metadata:
  name: objectscale-portal
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-portal
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/component: objectscale-portal
  ports: {{ toYaml .Values.service.ports | nindent 6 }}
{{- end }}


---
apiVersion: v1
kind: Service
metadata:
  name: objectscale-portal-external
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-portal
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/component: objectscale-portal
  ports: {{ toYaml .Values.service.ports | nindent 6 }}

---