{{- if .Values.useCustomValues }}
---
global:
  {{- if .Values.global.registrySecret }}
  registrySecret: {{ .Values.global.registrySecret }}
  {{- end }}

  registry: {{ .Values.global.registry }}

  watchAllNamespaces: {{ .Values.global.watchAllNamespaces }}

  objectscale_release_name: {{ .Values.global.objectscale_release_name }}

  rsyslog_client_stdout_enabled: {{ .Values.global.rsyslog_client_stdout_enabled }}

  platform: {{ .Values.global.platform }}

createApplicationResource: {{ .Values.createApplicationResource }}

{{- if .Values.logging_injector }}
## pull in any other custom values from the builder set with --set logging_injector.platform=OpenShift
{{ toYaml .Values.logging_injector }}
{{- end }}

{{- end }}
