---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kahm-app-config
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: "kahm"
    app.kubernetes.io/version: {{.Values.tag}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: nautilus
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    release: {{.Release.Name}}
  annotations:
    com.dellemc.kahm.subscribed: "true"
data:
  eventRules: |-
    issueRules:
{{ range $path, $_ :=  .Files.Glob  "alerts/issues/*_issue.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
    rules:
      - description: send all critical events to SNMP server
        matchon:
          - field: type
            operator: "=="
            value: Critical
        notifiers:
          - objectscale-snmp-notifier
      - description: send all error events to SNMP server
        matchon:
          - field: type
            operator: "=="
            value: Error
        notifiers:
          - objectscale-snmp-notifier
      - description: send all warning events to SNMP server
        matchon:
          - field: type
            operator: "=="
            value: Warning
        notifiers:
          - objectscale-snmp-notifier
  eventRemedies: |-
    symptoms:
{{ range $path, $_ :=  .Files.Glob  "alerts/remedies/*_remedies.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
  health: |-
    spec:
      - name: pre-update
        container: {{.Values.global.registry}}/{{.Values.healthChecks.preUpdate.image.repository}}:{{default .Values.tag .Values.healthChecks.preUpdate.image.tag}}
        serviceaccount: {{.Release.Name}}-healthchecks
        timelimit: "5m"
        reason: "pre-update"
        symptomID: "KAHM-HC-1000"
        args:
          - -target-version
          - {{ default .Values.tag .Values.healthChecks.preUpdate.image.tag }}
