---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kahm
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.registrySecret }}
imagePullSecrets:
  - name: {{ .Values.global.registrySecret }}
{{- end }}
---
{{- if eq .Values.global.watchAllNamespaces true }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-kahm
{{- if ne .Values.global.watchAllNamespaces true }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - kahm.emcecs.github.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - app.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  - batch
  - extensions
  resources:
  - pods
  - pods/log
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - configmaps/finalizers
  - secrets
  - applications
  - deployments
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
---
{{- if eq .Values.global.watchAllNamespaces true }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-kahm
{{- if ne .Values.global.watchAllNamespaces true }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: kahm
  namespace: {{ .Release.Namespace }}
roleRef:
{{- if eq .Values.global.watchAllNamespaces true }}
  kind: ClusterRole
{{- else }}
  kind: Role
{{- end }}
  name: {{ .Release.Namespace }}-kahm
  apiGroup: rbac.authorization.k8s.io
