---
apiVersion: v2
name: influxdb-operator
version: 0.79.0-1218
appVersion: 0.79.0-1218
description: |
  InfluxDB Operator deploys operator pod which is
  responsible for managing Influxdb custom resources
maintainers:
  - name: Dell EMC
    url: https://dellemc.com
dependencies:
  - name: common-monitoring-lib
    repository: https://asdrepo.isus.emc.com/artifactory/objectscale-helm-build/
    # rfw-update-next common-monitoring-lib-helm-chart
    version: 3.7.0-1278.7184b46e # no_auto_change__monitoring_auto_change
  - name: common-lib
    version: 0.79.0-1218
    repository: file://../common-lib
