---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decks
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
    name: decks
spec:
  replicas: 1
  selector:
    matchLabels:
      name: decks
  template:
    metadata:
      labels:
        name: decks
        app.kubernetes.io/name: "decks"
        release: {{ .Release.Name }}
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
    spec:
      serviceAccountName: "decks"
{{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
{{- end }}
      containers:
      - name: decks
{{- if .Values.image.tag }}
        image: {{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
{{- else }}
        image: {{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Values.tag }}
{{- end }}
{{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- else }}
        imagePullPolicy: {{ .Values.pullPolicy }}
{{- end }}
        command:
        - decks
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
{{- if eq .Values.global.watchAllNamespaces true }}
          value: ""
{{- else }}
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- end }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.global.registrySecret }}
        - name: REGISTRY_SECRET
          value: {{ .Values.global.registrySecret }}
{{- end }}
        - name: CONTROLLER_NAME
          value: decks
        - name: GC_POLLING_INTERVAL_IN_MIN
          value: "{{ .Values.supportStore.gcPollingInterval }}"
        - name: GC_FILE_AGE_TO_REMOVE_IN_DAYS
          value: "{{ .Values.supportStore.gcFileAgeToRemove }}"
