{{- if .Values.useCustomValues }}
---
global:
  {{- if .Values.global.registrySecret }}
  registrySecret: {{ .Values.global.registrySecret }}
  {{- end }}

  registry: {{ .Values.global.registry }}

  watchAllNamespaces: {{ .Values.global.watchAllNamespaces }}

  platform: {{ .Values.global.platform }}

storageClassName: {{ .Values.storageClassName }}

decks-support-store:
  persistentVolume:
    storageClassName: {{ index .Values "decks-support-store" "persistentVolume" "storageClassName" }}

createdecksappResource: {{ .Values.createdecksappResource }}

{{- if .Values.decks }}
## pull in any other custom values from the builder set with --set decks.image.tag=best-tag-evah
{{ toYaml .Values.decks }}
{{- end }}

{{- end }}