---
apiVersion: v2
appVersion: 2.80.0-1276
description: Helm chart for Dell Technologies KAHM SNMP Notifier
name: snmp-notifier
version: 2.80.0-1276
icon: https://avatars0.githubusercontent.com/u/12926680
maintainers:
  - name: Dell EMC
    url: http://dellemc.com
dependencies:
  - name: common-lib
    version: 0.80.0-1276 # no_auto_change__flex_auto_change
    repository: file://../common-lib
