{{- if .Values.useCustomValues }}
---
global:
  {{- if .Values.global.registrySecret }}
  registrySecret: {{ .Values.global.registrySecret }}
  {{- end }}

  registry: {{ .Values.global.registry }}

  watchAllNamespaces: {{ .Values.global.watchAllNamespaces }}

  platform: {{ .Values.global.platform }}

storageClassName: {{ .Values.storageClassName }}

postgresql-ha:
  persistence:
    storageClass: {{ index .Values "postgresql-ha" "persistence" "storageClass" }}

createkahmappResource: {{ .Values.createkahmappResource }}

{{- if .Values.kahm }}
## pull in any other custom values from the builder set with --set kahm.image.tag=best-tag-evah
{{ toYaml .Values.kahm }}
{{- end }}

{{- end }}
