---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-objectscale-federation-admin
  {{- if (eq .Values.global.watchAllNamespaces false) }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: objectscale-federation
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name}}
    operator: objectscale-operator
    product: objectscale
rules:
- apiGroups:
  - ecs.dellemc.com
  resources:
  - ecsclusters
  verbs:
  - "*"
- apiGroups:
  - app.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - "*"
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
    - configmaps
    - services
  verbs:
    - "*"
