---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: objectscale-federation
  labels:
    {{- include "fedsvc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fedsvc.replicaCount }}
  selector:
    matchLabels:
      {{- include "fedsvc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fedsvc.selectorLabels" . | nindent 8 }}
{{ include "common-lib.labels-sp-integrated-all" . | indent 8}}
      annotations:
{{ include "common-lib.vsphere-emm-integrated_annotation" . | indent 8}}
    spec:
      serviceAccountName: "objectscale-federation"
      {{- if .Values.global.registrySecret }}
      imagePullSecrets:
        - name: {{ .Values.global.registrySecret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        resources:
          limits:
            memory: 1000M
          requests:
            memory: 1000M
        env:
        - name: ATLAS_SERVICE_HOSTNAME
          value: {{ include "fedsvc.name" . }}-atlas-client
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_OBJECTSCALE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: {{ default  .Values.global.registry .Values.fedsvc.image.registry }}/{{ .Values.fedsvc.image.repository }}:{{ default .Values.tag .Values.fedsvc.image.tag }}
        imagePullPolicy: {{ .Values.fedsvc.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 9501 
            protocol: TCP
        livenessProbe:
            httpGet:
                path: {{ .Values.fedsvc.livenessProbe.probePath }}
                port: http
            failureThreshold: {{ .Values.fedsvc.livenessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.fedsvc.livenessProbe.periodSeconds | default 60 }}
            initialDelaySeconds: {{ .Values.fedsvc.livenessProbe.initialDelaySeconds | default 60 }}
        readinessProbe:
            httpGet:
                path: {{ .Values.fedsvc.readinessProbe.probePath }}
                port: http
            failureThreshold: {{ .Values.fedsvc.readinessProbe.failureThreshold | default 3 }}
            periodSeconds: {{ .Values.fedsvc.readinessProbe.periodSeconds | default 60 }}
            initialDelaySeconds: {{ .Values.fedsvc.readinessProbe.initialDelaySeconds | default 60 }}
        volumeMounts:
        - name: log
          mountPath: /opt/storageos/logs
        - name: config
          mountPath: /opt/storageos/conf/fedsvc-log4j2.xml
          subPath: fedsvc-log4j2.xml

      volumes:
        - name: log
          emptyDir: {}
        - name: config
          configMap:
            name: objectscale-federation-log-config
