---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: objectscale-federation
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: "objectscale-federation"
    app.kubernetes.io/version: {{.Values.tag}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    release: {{.Release.Name}}
{{- if .Values.global.registrySecret }}
imagePullSecrets:
  - name: {{ .Values.global.registrySecret }}
{{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{.Release.Namespace }}-objectscale-federation
{{- if ne .Values.global.watchAllNamespaces true }}
  namespace: {{.Release.Namespace}}
{{- end }}
  labels:
    app.kubernetes.io/name: "objectscale-federation"
    app.kubernetes.io/version: {{.Values.tag}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: objectscale-federation
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-objectscale-federation-admin
  apiGroup: rbac.authorization.k8s.io
