apiVersion: v1
kind: ConfigMap
metadata:
  name: objectscale-federation-log-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: objectscale-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: ecs-flex-manager
data:
  fedsvc-log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration monitorInterval="60" shutdownHook="disable">
        <Appenders>
            <RollingFile name="LogToFile" fileName="${sys:product.home}/logs/fedsvc.log"
                     filePattern="${sys:product.home}/logs/fedsvc.log.%i">
                <PatternLayout>
                    <Pattern>%d{ISO8601} [%t] %5p  %F (line %L) %m%n%ex</Pattern>
                </PatternLayout>
                <Policies>
                    <SizeBasedTriggeringPolicy size="5 MB"/>
                </Policies>
            </RollingFile>
        </Appenders>
        <Loggers>
            <Root level="INFO">
                <AppenderRef ref="LogToFile"/>
            </Root>
        </Loggers>
    </Configuration>
---
