---
apiVersion: v1
kind: Secret
metadata:
  name: objectscale-federation-trusted-anchors
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "fedsvc.labels" . | nindent 4 }}
type: Opaque
stringData:
