---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-fabric-proxy
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-fabric-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "csi-baremetal.dell.com"
    resources:
      - volumes
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-fabric-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-fabric-proxy
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-fabric-proxy
  apiGroup: rbac.authorization.k8s.io
