---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{.Release.Name}}-app-config
    namespace: {{.Release.namespace}}
    labels:
      app.kubernetes.io/name: {{.Release.Name}}
      app.kubernetes.io/version: {{.Values.tag}}
      app.kubernetes.io/instance: {{.Release.Name}}
      app.kubernetes.io/managed-by: {{.Release.Service}}
      helm.sh/chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
      product: objectscale
      release: {{.Release.Name}}
    annotations:
        com.dellemc.kahm.subscribed: "true"
data:
    eventRules: |-
      issueRules:
{{ range $path, $_ :=  .Files.Glob  "alerts/issues/*_issue.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
      rules:
        - description: send all critical events to SNMP server
          matchon:
            - field: type
              operator: "=="
              value: Critical
          notifiers:
            - objectscale-snmp-notifier
        - description: send all error events to SNMP server
          matchon:
            - field: type
              operator: "=="
              value: Error
          notifiers:
            - objectscale-snmp-notifier
        - description: send all warning events to SNMP server
          matchon:
            - field: type
              operator: "=="
              value: Warning
          notifiers:
            - objectscale-snmp-notifier

    eventRemedies: |-
      symptoms:
{{ range $path, $_ :=  .Files.Glob  "alerts/remedies/*_remedies.yaml" }}
{{- $.Files.Get $path | indent 8 }}
{{ end }}
    health: |-
      spec:
        - name: healthcheck
          container: {{.Values.global.registry}}/{{.Values.healthChecks.connectivity.image.repository}}:{{default .Values.tag .Values.healthChecks.connectivity.image.tag}}
          serviceaccount: {{.Release.Name}}-healthchecks
          schedule: "0 */6 * * *"
          timelimit: "5m"
          args:
            - all
        - name: pre-update
          container: {{.Values.global.registry}}/{{.Values.healthChecks.preUpdate.image.repository}}:{{default .Values.tag .Values.healthChecks.preUpdate.image.tag}}
          serviceaccount: {{.Release.Name}}-healthchecks
          timelimit: "5m"
          reason: "pre-update"
          symptomID: "OBJSTORE-HC-1000"
          args:
            - -target-version
            - {{ default .Values.tag .Values.healthChecks.preUpdate.image.tag }}
        - name: post-upgrade
          container: {{.Values.global.registry}}/{{.Values.healthChecks.postUpgrade.image.repository}}:{{default .Values.tag .Values.healthChecks.postUpgrade.image.tag}}
          serviceaccount: {{.Release.Name}}-healthchecks
          timelimit: "20m"
