---
apiVersion: v1
kind: Secret
metadata:
  name: objectscale-gateway-tls
  namespace: {{ .Release.Namespace}}
  annotations:
    certificateType: "SelfSigned"
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "objectscaleGateway.labels" . | nindent 4 }}
type: Opaque
stringData:
