---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: supportassists.decks.ecs.dellemc.com
spec:
  group: decks.ecs.dellemc.com
  names:
    kind: SupportAssist
    listKind: SupportAssistList
    plural: supportassists
    singular: supportassist
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: PHASE
      type: string
      description: The current phase of SupportAssist
      JSONPath: .status.phase
