---
apiVersion: v1
kind: Secret
metadata:
  name: objectscale-iam-tls
  namespace: {{ .Release.Namespace}}
  annotations:
    certificateType: "InternallySigned"
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    {{- include "iam.labels" . | nindent 4 }}
type: Opaque
stringData:

